version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Type: Chore"
    commit-message:
      prefix: "[C]"
    ignore:
      # ignore all keycloak-js updates
      # keycloak-js updates are incompatible with @react-keycloak/ssr
      - dependency-name: "keycloak-js"
